spring.application.name=Briliq Payment Service
spring:
datasource:
url: jdbc:h2:mem:briliqdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
driver-class-name: org.h2.Driver
username: sa
password:
jpa:
hibernate:
ddl-auto: update
show-sql: true
server:
port: 8081
xendit:
secret-key: ${XENDIT_SECRET_KEY:dummy_key}
